// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AdaptPaths(arg1:string,arg2:Array<string>):Promise<string>;

export function AnalyzeScripts(arg1:string):Promise<Array<string>>;

export function DeleteSite(arg1:string):Promise<string>;

export function DownloadSite(arg1:string,arg2:string):Promise<string>;

export function GetDownloads():Promise<Array<main.SiteMeta>>;

export function LaunchSite(arg1:string):Promise<string>;

export function OpenFolder(arg1:string):Promise<void>;

export function SelectFolder():Promise<string>;

export function StartServer(arg1:string,arg2:string):Promise<string>;

export function StopServer():Promise<string>;
