// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdaptPaths(arg1, arg2) {
  return window['go']['main']['App']['AdaptPaths'](arg1, arg2);
}

export function AnalyzeScripts(arg1) {
  return window['go']['main']['App']['AnalyzeScripts'](arg1);
}

export function DeleteSite(arg1) {
  return window['go']['main']['App']['DeleteSite'](arg1);
}

export function DownloadSite(arg1, arg2) {
  return window['go']['main']['App']['DownloadSite'](arg1, arg2);
}

export function GetDownloads() {
  return window['go']['main']['App']['GetDownloads']();
}

export function LaunchSite(arg1) {
  return window['go']['main']['App']['LaunchSite'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StartServer(arg1, arg2) {
  return window['go']['main']['App']['StartServer'](arg1, arg2);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
